services:
  - type: web
    name: roshi-fit-club
    env: node
    envVars:
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 